Clean up format and style, prepare for Databricks runtime
henrikbulldog/spark.org.anonymizer pull request #6
Opened 2021-06-24 09:25 UTC by henrikbulldog

2021-06-25 05:35 UTC, Rajesh2015 approved these changes
LGTM

2021-06-25 05:37 UTC, Rajesh2015 commented
@henrikbulldog I see the sparksession is never closed in test class after the test ends though I donot see any side effects  .is it intentional .

2021-06-25 05:37 UTC, sudhanshurocky approved these changes

2021-06-25 14:57 UTC, Rajesh2015 requested changes
test data names are having issue

2021-06-25 14:57 UTC, Rajesh2015 commented on src/test/scala/org/spark/NameConverterTest.scala
> +  val firstNames = Source.fromFile("src/test/scala/org/spark/data/firstNames.txt").getLines.toSeq
@henrikbulldog Test cases are failing as the txt file name has discrepancy (Uppercase Lower Case)

2021-06-25 14:57 UTC, Rajesh2015 commented on src/test/scala/org/spark/NameConverterTest.scala
> +  val lastNames = Source.fromFile("src/test/scala/org/spark/data/lastNames.txt").getLines.toSeq
Same as previous

2021-06-28 08:48 UTC, Rajesh2015 approved these changes
LGTM

2021-06-28 08:51 UTC, sudhanshurocky approved these changes

2021-06-28 09:19 UTC, merged